name: Modelops deploy

on:  # ante que operaciones de va a ejecutar/disparar
  push:    # git push origin main/master
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: adsoft/aiops:latest

    steps:
    - uses: actions/checkout@v2
    - name: hello-world
      run: echo "hello world workflows "

